bash ./runsh/chinese-macbert-base/chinese-macbert-base.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-fgm.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-pgd-3.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-rdrop-1.0.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-warmup-0.1.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-rdrop-0.5.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-rdrop-0.1.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-ema-0.99.sh
bash ./runsh/chinese-macbert-base/chinese-macbert-base-ema-0.999.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-ema-0.99.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-rdrop-0.1.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-pgd-3.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-ema-0.999.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-rdrop-1.0.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-warmup-0.1.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-rdrop-0.5.sh
bash ./runsh/chinese-roberta-wwm-ext/chinese-roberta-wwm-ext-fgm.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-warmup-0.1.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-ema-0.999.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-rdrop-1.0.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-rdrop-0.5.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-ema-0.99.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-rdrop-0.1.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-fgm.sh
bash ./runsh/ernie-3.0-base-zh/ernie-3.0-base-zh-pgd-3.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-rdrop-0.1.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-rdrop-1.0.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-pgd-3.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-ema-0.99.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-ema-0.999.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-fgm.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-warmup-0.1.sh
bash ./runsh/mengzi-bert-base/mengzi-bert-base-rdrop-0.5.sh
